### ISSUE TITLE
Null object error on new website. 

### ISSUE THREAD

**Issue by haroonlatif** [PiranhaCMS/Piranha#436] opened 2015-08-04 10:56 UTC
Hi,
I have created empty mvc website. 
Added nuget for piranha cms mvc template package. 
created new db and updated connection string. 
started the app from VS 2013 and enteretd the user details.
first it gives me the error that website is in redirect loop. 
I killed the session and try to restart it again from VS and got the following error. 

I can see it has created tables in db. 

let me know if you have any questions. 

[NullReferenceException: Object reference not set to an instance of an object.]
   Piranha.Mvc.SinglePageController.OnActionExecuting(ActionExecutingContext context) +946
   System.Web.Mvc.Controller.System.Web.Mvc.IActionFilter.OnActionExecuting(ActionExecutingContext filterContext) +39
   System.Web.Mvc.Async.AsyncInvocationWithFilters.InvokeActionMethodFilterAsynchronouslyRecursive(Int32 filterIndex) +406
   System.Web.Mvc.Async.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__31(AsyncCallback asyncCallback, Object asyncState) +142
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallBeginDelegate(AsyncCallback callback, Object callbackState) +59
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout) +151

**Comment by tidyui** [comment] 2015-08-08 06:03
This is probably a duplicate of this issue #417 which is a bug that occurs after a clean install. Just restart the Application Pool by saving your web.config

**Closed** 2015-09-08 20:22 UTC
Labels: duplicate
